DROP TABLE IF EXISTS LGA;
DROP TABLE IF EXISTS HOMELESS;
DROP TABLE IF EXISTS AT_RISK;
DROP TABLE IF EXISTS UNKNOWN;
DROP TABLE IF EXISTS POPULATION;

CREATE TABLE LGA (
    LGA_CODE    INT NOT NULL, 
    LGA_NAME    VARCHAR(255),
    LGA_TYPE    CHAR(2),
    AREA        DOUBLE,
    LATITUDE    DOUBLE,
    LONGITUDE   DOUBLE,
    PRIMARY KEY (LGA_CODE)
);

CREATE TABLE HOMELESS (
    YEAR        INT NOT NULL,
    SEX         VARCHAR (1) NOT NULL, 
    AGE_GROUP   VARCHAR(10) NOT NULL,
    COUNT       INT,
    LGA_CODE    INT NOT NULL,
    PRIMARY KEY (YEAR, SEX, AGE_GROUP)
    FOREIGN KEY (LGA_CODE) REFERENCES LGA(LGA_CODE)
);

CREATE TABLE AT_RISK (
    YEAR        INT NOT NULL,
    SEX         VARCHAR (1) NOT NULL, 
    AGE_GROUP   VARCHAR(10) NOT NULL,
    COUNT       INT,
    LGA_CODE    INT NOT NULL,
    PRIMARY KEY (YEAR, SEX, AGE_GROUP)
    FOREIGN KEY (LGA_CODE) REFERENCES LGA(LGA_CODE)
);

CREATE TABLE UNKNOWN (
    YEAR        INT NOT NULL,
    COUNT       INT,
    LGA_CODE    INT NOT NULL,
    PRIMARY KEY (YEAR)
    FOREIGN KEY (LGA_CODE) REFERENCES LGA (LGA_CODE) 
);

CREATE TABLE POPULATION (
    YEAR        INT NOT NULL,
    POPULATION  LONG,
    LGA_CODE    INT,
    PRIMARY KEY (YEAR)
    FOREIGN KEY (LGA_CODE) REFERENCES LGA(LGA_CODE)
);

CREATE TABLE INCOME (
    YEAR                            INT NOT NULL,
    MEDIAN_WEEKLY_INCOME            INT,
    MEDIAN_AGE                      INT,
    MEDIAN_MORTAGE_REPAY_MONTHLY    INT,
    MEDIAN_RENT_WEEKLY              INT,
    LGA_CODE                        INT NOT NULL,
    PRIMARY KEY (YEAR)
    FOREIGN KEY (LGA_CODE) REFERENCES LGA (LGA_CODE)
);